kind: SriovOperatorConfig
apiVersion: sriovnetwork.openshift.io/v1
metadata:
  name: default
  namespace: openshift-sriov-network-operator
spec:
  configurationMode: daemon
  disableDrain: false
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 2
  # Note: maxUnavailable is not supported in SR-IOV operator v1.x
  # By default, nodes are updated one at a time (serial updates)
