apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-training

resources:
  - dsp-example-imagestream.yaml
  - dsp-example-pipeline.yaml
  - dsp-example-pipelinerun.yaml
  - dsp-example-rbac.yaml
  - execute-kfp-task.yaml
