apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base-infra-nodes
- ../../overlays/pipelines-1.8

patches:
  - path: patch-subscription-infra-nodes.yaml
    target:
      kind: Subscription
