apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook
    newTag: "2024.1"

replacements:
  - source:
      kind: Notebook
      group: kubeflow.org
      name: example-workbench
      fieldPath: spec.template.spec.containers.[name=example-workbench].image
    targets:
      - select:
          kind: Notebook
          group: kubeflow.org
          name: example-workbench
        fieldPaths:
          - spec.template.spec.containers.[name=example-workbench].env.[name=JUPYTER_IMAGE].value
