apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-single-model-serving

resources:
  - ../../../../components/apps/minio/overlays/default
  - ../../base/
  - ../../examples/tgis-flan-single-model-server
