apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - ../../../components/argocd/apps/overlays/rhoai-stable-2.19

# patches:
#   Uncomment patches to disable automatic sync
#   - path: patch-applicationset-manual-sync.yaml
#     target:
#       group: argoproj.io
#       version: v1alpha1
#       kind: ApplicationSet
#   - path: patch-application-manual-sync.yaml
#     target:
#       group: argoproj.io
#       kind: Application
#       version: v1alpha1

replacements:
  # copy the repo from the application to the applicationsets
  - source:
      kind: Application
      fieldPath: spec.source.repoURL
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.template.spec.source.repoURL
      - select:
          kind: ApplicationSet
          name: tenants
        fieldPaths:
          - spec.generators.*.git.repoURL
  # copy the branch from the application to the applicationsets
  - source:
      kind: Application
      fieldPath: spec.source.targetRevision
    targets:
      - select:
          kind: ApplicationSet
        fieldPaths:
          - spec.template.spec.source.targetRevision
      - select:
          kind: ApplicationSet
          name: tenants
        fieldPaths:
          - spec.generators.*.git.revision
