apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - ../../../components/argocd/apps/overlays/rhoai-eus-2.16-baremetal

replacements:
  # copy the repo from the application to the standard applicationsets
  - source:
      kind: Application
      fieldPath: spec.source.repoURL
    targets:
      - select:
          kind: ApplicationSet
          name: cluster-.*
        fieldPaths:
          - spec.template.spec.source.repoURL
        options:
          delimiter: "-"
      - select:
          kind: ApplicationSet
          name: baremetal-.*
        fieldPaths:
          - spec.template.spec.source.repoURL
          - metadata.annotations.source_repo_url
        options:
          delimiter: "-"
  # copy the branch from the application to the applicationsets
  - source:
      kind: Application
      fieldPath: spec.source.targetRevision
    targets:
      - select:
          kind: ApplicationSet
          name: cluster-.*
        fieldPaths:
          - spec.template.spec.source.targetRevision
        options:
          delimiter: "-"
      - select:
          kind: ApplicationSet
          name: baremetal-.*
        fieldPaths:
          - spec.template.spec.source.targetRevision
          - metadata.annotations.source_target_revision
        options:
          delimiter: "-"
