apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-single-model-serving

resources:
  - ./setup-jobs
  - data-connection.yaml
  - inference-service.yaml
  - serving-runtime.yaml

patches:
  - path: patch-model-details.yaml
    target:
      kind: Job
      name: upload-model-to-s3-vllm

replacements:
  - source:
      kind: Secret
      name: aws-connection-vllm
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: create-buckets-vllm
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
      - select:
          kind: Job
          name: upload-model-to-s3-vllm
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
