apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/wait-for-prereqs

patches:
  - target:
      kind: Subscription
      name: rhods-operator
    path: patch-channel.yaml
