---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kuadrant-system

resources:
  - ../../components/wait-for-servicemesh
  - kuadrant-system-namespace.yaml
  - kuadrant.yaml
