apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-datasciencecluster-health-check.yaml
    target:
      kind: ArgoCD
  - path: patch-datasciencepipelineapplication-health-check.yaml
    target:
      kind: ArgoCD