apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: kuadrant-system

resources:
- wait-for-servicemesh-job.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/hook: PreSync

configMapGenerator:
  - name: wait-for-servicemesh
    namespace: kuadrant-system
    files:
      - wait-for-servicemesh.sh
