apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/auth-with-authorino
  - ../../components/components-distributed-compute
  - ../../components/components-kserve
  - ../../components/components-training
  - ../../components/components-trustyai
  - ../../components/dashboard-feature-hardware-profiles
  - ../../components/dashboard-feature-model-catalog
  - ../../components/default-notebook-pvc-size
  - ../../components/nvidia-gpu-hardware-profile
  - ../../components/idle-notebook-culling
  - ../../components/notebook-pod-sizes
  - ../../components/make-kubeadmin-cluster-admin
  - ../../components/model-server-pod-sizes
  - ../../components/rhoai-auth
