apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-100"

labels:
  - includeSelectors: true
    pairs:
      app: minio
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: minio

resources:
  - deployment.yaml
  - pvc.yaml
  - routes.yaml
  - secret.yaml
  - service.yaml
