apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - ../../../components/argocd/apps/overlays/rhoai-fast-aws-gpu

patches:
  - path: patch-applicationset-repo-revision.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      version: v1alpha1
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      kind: Application
      version: v1alpha1
  # Uncomment patches to disable automatic sync
  - path: patch-applicationset-manual-sync.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
  - path: patch-application-manual-sync.yaml
    target:
      group: argoproj.io
      kind: Application
      version: v1alpha1
