apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: nvidia-gpu-operator

resources:
  - setup-machineset-job.yaml
  - setup-machineset-rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: create-gpu-machineset
    files:
      - create-gpu-machineset.sh
