apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: redhat-ods-operator

resources:
- wait-for-prereqs-job.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/hook: PreSync

configMapGenerator:
  - name: wait-for-prereqs
    namespace: redhat-ods-operator
    files:
      - wait-for-prereqs.sh
